### PR TITLE
added several missing translation dependencies and updated dict/en an…

### PR DESCRIPTION
**Pull request by BerChill**
…d dict/de accordingly

NOTE: My changes should be reviewed thoroughly since they are based on a possibly faulty version of master as described in #202 . I just noticed this after working on it otherwise I would have waited for a fixed version of master. But the testing I did suggests that no additional errors have been introduced by my changes.

### CODE REVIEW

**Comment by Alanaktion** [comment]
This appears to revert the changes made in 6c2efdd45d8cae056be5bd199107848a956b5cc7 and 06b8fd2ebde5ee0e9652372ed254ea3e416d6fc8. Make sure you've merged the upstream changes correctly, the other changes you've made look good.

**Comment by BerChill** [comment]
Got the upstream master merged and added some more dependencies. Hope this is correct now. Sorry if not ... I'm quite new to collaborative coding :)

**Comment by Alanaktion** [comment]
It still looks a bit off. You may have had a merge conflict at some point that was resolved incorrectly, causing your current code to replace the changes in the upstream code. This can be resolved by checking out the upstream master and re-making your changes to that code, since your commit history already has the conflict.
If you'd prefer, I can fix the issues in the merge directly myself. No big deal either way :smile:

**Comment by BerChill** [comment]
Thanks, I'll try to do it myself as long as you don't mind the time it takes to review it everytime I mess up :smile: . Need to get comfortable doing this kinda stuff anyway.

**Pull request closed without merging**
